# Generated by Django 3.1.4 on 2020-12-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfast',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dinner',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lunch',
            name='calories',
            field=models.IntegerField(default=0),
        ),
    ]
