# Generated by Django 3.1.4 on 2020-12-05 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_auto_20201205_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakfast',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='dinner',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='lunch',
            name='calories',
        ),
    ]
